# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dooz/projects/citygen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dooz/projects/citygen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dooz/projects/citygen/CMakeFiles /Users/dooz/projects/citygen/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dooz/projects/citygen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named citygen

# Build rule for target.
citygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 citygen
.PHONY : citygen

# fast build rule for target.
citygen/fast:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/build
.PHONY : citygen/fast

citygen.o: citygen.cpp.o
.PHONY : citygen.o

# target to build an object file
citygen.cpp.o:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/citygen.cpp.o
.PHONY : citygen.cpp.o

citygen.i: citygen.cpp.i
.PHONY : citygen.i

# target to preprocess a source file
citygen.cpp.i:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/citygen.cpp.i
.PHONY : citygen.cpp.i

citygen.s: citygen.cpp.s
.PHONY : citygen.s

# target to generate assembly for a file
citygen.cpp.s:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/citygen.cpp.s
.PHONY : citygen.cpp.s

file_utils.o: file_utils.cpp.o
.PHONY : file_utils.o

# target to build an object file
file_utils.cpp.o:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/file_utils.cpp.o
.PHONY : file_utils.cpp.o

file_utils.i: file_utils.cpp.i
.PHONY : file_utils.i

# target to preprocess a source file
file_utils.cpp.i:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/file_utils.cpp.i
.PHONY : file_utils.cpp.i

file_utils.s: file_utils.cpp.s
.PHONY : file_utils.s

# target to generate assembly for a file
file_utils.cpp.s:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/file_utils.cpp.s
.PHONY : file_utils.cpp.s

imgui.o: imgui.cpp.o
.PHONY : imgui.o

# target to build an object file
imgui.cpp.o:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/imgui.cpp.o
.PHONY : imgui.cpp.o

imgui.i: imgui.cpp.i
.PHONY : imgui.i

# target to preprocess a source file
imgui.cpp.i:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/imgui.cpp.i
.PHONY : imgui.cpp.i

imgui.s: imgui.cpp.s
.PHONY : imgui.s

# target to generate assembly for a file
imgui.cpp.s:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/imgui.cpp.s
.PHONY : imgui.cpp.s

imguiRenderGL.o: imguiRenderGL.cpp.o
.PHONY : imguiRenderGL.o

# target to build an object file
imguiRenderGL.cpp.o:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/imguiRenderGL.cpp.o
.PHONY : imguiRenderGL.cpp.o

imguiRenderGL.i: imguiRenderGL.cpp.i
.PHONY : imguiRenderGL.i

# target to preprocess a source file
imguiRenderGL.cpp.i:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/imguiRenderGL.cpp.i
.PHONY : imguiRenderGL.cpp.i

imguiRenderGL.s: imguiRenderGL.cpp.s
.PHONY : imguiRenderGL.s

# target to generate assembly for a file
imguiRenderGL.cpp.s:
	$(MAKE) -f CMakeFiles/citygen.dir/build.make CMakeFiles/citygen.dir/imguiRenderGL.cpp.s
.PHONY : imguiRenderGL.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... citygen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... citygen.o"
	@echo "... citygen.i"
	@echo "... citygen.s"
	@echo "... file_utils.o"
	@echo "... file_utils.i"
	@echo "... file_utils.s"
	@echo "... imgui.o"
	@echo "... imgui.i"
	@echo "... imgui.s"
	@echo "... imguiRenderGL.o"
	@echo "... imguiRenderGL.i"
	@echo "... imguiRenderGL.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

