// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "city.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace citygen {
namespace protocol {

namespace {

const ::google::protobuf::Descriptor* Vector3_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Vector3_reflection_ = NULL;
const ::google::protobuf::Descriptor* CellParameterSet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CellParameterSet_reflection_ = NULL;
const ::google::protobuf::Descriptor* StepSettings_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StepSettings_reflection_ = NULL;
const ::google::protobuf::Descriptor* TerrainSettings_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TerrainSettings_reflection_ = NULL;
const ::google::protobuf::Descriptor* Settings_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Settings_reflection_ = NULL;
const ::google::protobuf::Descriptor* City_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  City_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_city_2eproto() {
  protobuf_AddDesc_city_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "city.proto");
  GOOGLE_CHECK(file != NULL);
  Vector3_descriptor_ = file->message_type(0);
  static const int Vector3_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector3, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector3, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector3, z_),
  };
  Vector3_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Vector3_descriptor_,
      Vector3::default_instance_,
      Vector3_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector3, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector3, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Vector3));
  CellParameterSet_descriptor_ = file->message_type(1);
  static const int CellParameterSet_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, cell_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, segment_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, segment_size_deviation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, degree_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, degree_deviation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, snap_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, snap_size_deviation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, connectivity_),
  };
  CellParameterSet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CellParameterSet_descriptor_,
      CellParameterSet::default_instance_,
      CellParameterSet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellParameterSet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CellParameterSet));
  StepSettings_descriptor_ = file->message_type(2);
  static const int StepSettings_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StepSettings, num_segments_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StepSettings, step_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StepSettings, deviation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StepSettings, road_height_),
  };
  StepSettings_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StepSettings_descriptor_,
      StepSettings::default_instance_,
      StepSettings_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StepSettings, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StepSettings, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StepSettings));
  TerrainSettings_descriptor_ = file->message_type(3);
  static const int TerrainSettings_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TerrainSettings, scale_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TerrainSettings, height_scale_),
  };
  TerrainSettings_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TerrainSettings_descriptor_,
      TerrainSettings::default_instance_,
      TerrainSettings_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TerrainSettings, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TerrainSettings, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TerrainSettings));
  Settings_descriptor_ = file->message_type(4);
  static const int Settings_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settings, terrain_settings_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settings, step_settings_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settings, cell_parameter_set_),
  };
  Settings_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Settings_descriptor_,
      Settings::default_instance_,
      Settings_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settings, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settings, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Settings));
  City_descriptor_ = file->message_type(5);
  static const int City_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(City, settings_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(City, nodes_),
  };
  City_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      City_descriptor_,
      City::default_instance_,
      City_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(City, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(City, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(City));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_city_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Vector3_descriptor_, &Vector3::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CellParameterSet_descriptor_, &CellParameterSet::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StepSettings_descriptor_, &StepSettings::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TerrainSettings_descriptor_, &TerrainSettings::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Settings_descriptor_, &Settings::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    City_descriptor_, &City::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_city_2eproto() {
  delete Vector3::default_instance_;
  delete Vector3_reflection_;
  delete CellParameterSet::default_instance_;
  delete CellParameterSet_reflection_;
  delete StepSettings::default_instance_;
  delete StepSettings_reflection_;
  delete TerrainSettings::default_instance_;
  delete TerrainSettings_reflection_;
  delete Settings::default_instance_;
  delete Settings_reflection_;
  delete City::default_instance_;
  delete City_reflection_;
}

void protobuf_AddDesc_city_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\ncity.proto\022\020citygen.protocol\"*\n\007Vector"
    "3\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"\350\001\n\020C"
    "ellParameterSet\022\017\n\007cell_id\030\001 \001(\005\022\030\n\014segm"
    "ent_size\030\002 \001(\002:\00210\022#\n\026segment_size_devia"
    "tion\030\003 \001(\002:\0030.5\022\021\n\006degree\030\004 \001(\005:\0012\022\035\n\020de"
    "gree_deviation\030\005 \001(\002:\0030.5\022\025\n\tsnap_size\030\006"
    " \001(\002:\00220\022 \n\023snap_size_deviation\030\007 \001(\002:\0030"
    ".5\022\031\n\014connectivity\030\010 \001(\002:\0030.3\"s\n\014StepSet"
    "tings\022\030\n\014num_segments\030\001 \001(\005:\00220\022\026\n\tstep_"
    "size\030\002 \001(\002:\0030.5\022\031\n\tdeviation\030\003 \001(\002:\0060.78"
    "54\022\026\n\013road_height\030\004 \001(\002:\0015\"6\n\017TerrainSet"
    "tings\022\r\n\005scale\030\001 \001(\002\022\024\n\014height_scale\030\002 \001"
    "(\002\"\276\001\n\010Settings\022;\n\020terrain_settings\030\001 \001("
    "\0132!.citygen.protocol.TerrainSettings\0225\n\r"
    "step_settings\030\002 \001(\0132\036.citygen.protocol.S"
    "tepSettings\022>\n\022cell_parameter_set\030\003 \003(\0132"
    "\".citygen.protocol.CellParameterSet\"^\n\004C"
    "ity\022,\n\010settings\030\001 \001(\0132\032.citygen.protocol"
    ".Settings\022(\n\005nodes\030\002 \003(\0132\031.citygen.proto"
    "col.Vector3", 771);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "city.proto", &protobuf_RegisterTypes);
  Vector3::default_instance_ = new Vector3();
  CellParameterSet::default_instance_ = new CellParameterSet();
  StepSettings::default_instance_ = new StepSettings();
  TerrainSettings::default_instance_ = new TerrainSettings();
  Settings::default_instance_ = new Settings();
  City::default_instance_ = new City();
  Vector3::default_instance_->InitAsDefaultInstance();
  CellParameterSet::default_instance_->InitAsDefaultInstance();
  StepSettings::default_instance_->InitAsDefaultInstance();
  TerrainSettings::default_instance_->InitAsDefaultInstance();
  Settings::default_instance_->InitAsDefaultInstance();
  City::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_city_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_city_2eproto {
  StaticDescriptorInitializer_city_2eproto() {
    protobuf_AddDesc_city_2eproto();
  }
} static_descriptor_initializer_city_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Vector3::kXFieldNumber;
const int Vector3::kYFieldNumber;
const int Vector3::kZFieldNumber;
#endif  // !_MSC_VER

Vector3::Vector3()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Vector3::InitAsDefaultInstance() {
}

Vector3::Vector3(const Vector3& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Vector3::SharedCtor() {
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Vector3::~Vector3() {
  SharedDtor();
}

void Vector3::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Vector3::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Vector3::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Vector3_descriptor_;
}

const Vector3& Vector3::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_city_2eproto();
  return *default_instance_;
}

Vector3* Vector3::default_instance_ = NULL;

Vector3* Vector3::New() const {
  return new Vector3;
}

void Vector3::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    x_ = 0;
    y_ = 0;
    z_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Vector3::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float x = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_y;
        break;
      }

      // optional float y = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_z;
        break;
      }

      // optional float z = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
          set_has_z();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Vector3::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional float x = 1;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // optional float y = 2;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // optional float z = 3;
  if (has_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->z(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Vector3::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional float x = 1;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // optional float y = 2;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // optional float z = 3;
  if (has_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->z(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Vector3::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional float x = 1;
    if (has_x()) {
      total_size += 1 + 4;
    }

    // optional float y = 2;
    if (has_y()) {
      total_size += 1 + 4;
    }

    // optional float z = 3;
    if (has_z()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Vector3::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Vector3* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Vector3*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Vector3::MergeFrom(const Vector3& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_z()) {
      set_z(from.z());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Vector3::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Vector3::CopyFrom(const Vector3& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vector3::IsInitialized() const {

  return true;
}

void Vector3::Swap(Vector3* other) {
  if (other != this) {
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(z_, other->z_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Vector3::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Vector3_descriptor_;
  metadata.reflection = Vector3_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CellParameterSet::kCellIdFieldNumber;
const int CellParameterSet::kSegmentSizeFieldNumber;
const int CellParameterSet::kSegmentSizeDeviationFieldNumber;
const int CellParameterSet::kDegreeFieldNumber;
const int CellParameterSet::kDegreeDeviationFieldNumber;
const int CellParameterSet::kSnapSizeFieldNumber;
const int CellParameterSet::kSnapSizeDeviationFieldNumber;
const int CellParameterSet::kConnectivityFieldNumber;
#endif  // !_MSC_VER

CellParameterSet::CellParameterSet()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CellParameterSet::InitAsDefaultInstance() {
}

CellParameterSet::CellParameterSet(const CellParameterSet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CellParameterSet::SharedCtor() {
  _cached_size_ = 0;
  cell_id_ = 0;
  segment_size_ = 10;
  segment_size_deviation_ = 0.5f;
  degree_ = 2;
  degree_deviation_ = 0.5f;
  snap_size_ = 20;
  snap_size_deviation_ = 0.5f;
  connectivity_ = 0.3f;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CellParameterSet::~CellParameterSet() {
  SharedDtor();
}

void CellParameterSet::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CellParameterSet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CellParameterSet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CellParameterSet_descriptor_;
}

const CellParameterSet& CellParameterSet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_city_2eproto();
  return *default_instance_;
}

CellParameterSet* CellParameterSet::default_instance_ = NULL;

CellParameterSet* CellParameterSet::New() const {
  return new CellParameterSet;
}

void CellParameterSet::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    cell_id_ = 0;
    segment_size_ = 10;
    segment_size_deviation_ = 0.5f;
    degree_ = 2;
    degree_deviation_ = 0.5f;
    snap_size_ = 20;
    snap_size_deviation_ = 0.5f;
    connectivity_ = 0.3f;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CellParameterSet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 cell_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cell_id_)));
          set_has_cell_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_segment_size;
        break;
      }

      // optional float segment_size = 2 [default = 10];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_segment_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &segment_size_)));
          set_has_segment_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_segment_size_deviation;
        break;
      }

      // optional float segment_size_deviation = 3 [default = 0.5];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_segment_size_deviation:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &segment_size_deviation_)));
          set_has_segment_size_deviation();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_degree;
        break;
      }

      // optional int32 degree = 4 [default = 2];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_degree:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &degree_)));
          set_has_degree();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(45)) goto parse_degree_deviation;
        break;
      }

      // optional float degree_deviation = 5 [default = 0.5];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_degree_deviation:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &degree_deviation_)));
          set_has_degree_deviation();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(53)) goto parse_snap_size;
        break;
      }

      // optional float snap_size = 6 [default = 20];
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_snap_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &snap_size_)));
          set_has_snap_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(61)) goto parse_snap_size_deviation;
        break;
      }

      // optional float snap_size_deviation = 7 [default = 0.5];
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_snap_size_deviation:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &snap_size_deviation_)));
          set_has_snap_size_deviation();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(69)) goto parse_connectivity;
        break;
      }

      // optional float connectivity = 8 [default = 0.3];
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_connectivity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &connectivity_)));
          set_has_connectivity();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CellParameterSet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 cell_id = 1;
  if (has_cell_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cell_id(), output);
  }

  // optional float segment_size = 2 [default = 10];
  if (has_segment_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->segment_size(), output);
  }

  // optional float segment_size_deviation = 3 [default = 0.5];
  if (has_segment_size_deviation()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->segment_size_deviation(), output);
  }

  // optional int32 degree = 4 [default = 2];
  if (has_degree()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->degree(), output);
  }

  // optional float degree_deviation = 5 [default = 0.5];
  if (has_degree_deviation()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->degree_deviation(), output);
  }

  // optional float snap_size = 6 [default = 20];
  if (has_snap_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->snap_size(), output);
  }

  // optional float snap_size_deviation = 7 [default = 0.5];
  if (has_snap_size_deviation()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->snap_size_deviation(), output);
  }

  // optional float connectivity = 8 [default = 0.3];
  if (has_connectivity()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(8, this->connectivity(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CellParameterSet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 cell_id = 1;
  if (has_cell_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cell_id(), target);
  }

  // optional float segment_size = 2 [default = 10];
  if (has_segment_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->segment_size(), target);
  }

  // optional float segment_size_deviation = 3 [default = 0.5];
  if (has_segment_size_deviation()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->segment_size_deviation(), target);
  }

  // optional int32 degree = 4 [default = 2];
  if (has_degree()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->degree(), target);
  }

  // optional float degree_deviation = 5 [default = 0.5];
  if (has_degree_deviation()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->degree_deviation(), target);
  }

  // optional float snap_size = 6 [default = 20];
  if (has_snap_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->snap_size(), target);
  }

  // optional float snap_size_deviation = 7 [default = 0.5];
  if (has_snap_size_deviation()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->snap_size_deviation(), target);
  }

  // optional float connectivity = 8 [default = 0.3];
  if (has_connectivity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(8, this->connectivity(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CellParameterSet::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 cell_id = 1;
    if (has_cell_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cell_id());
    }

    // optional float segment_size = 2 [default = 10];
    if (has_segment_size()) {
      total_size += 1 + 4;
    }

    // optional float segment_size_deviation = 3 [default = 0.5];
    if (has_segment_size_deviation()) {
      total_size += 1 + 4;
    }

    // optional int32 degree = 4 [default = 2];
    if (has_degree()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->degree());
    }

    // optional float degree_deviation = 5 [default = 0.5];
    if (has_degree_deviation()) {
      total_size += 1 + 4;
    }

    // optional float snap_size = 6 [default = 20];
    if (has_snap_size()) {
      total_size += 1 + 4;
    }

    // optional float snap_size_deviation = 7 [default = 0.5];
    if (has_snap_size_deviation()) {
      total_size += 1 + 4;
    }

    // optional float connectivity = 8 [default = 0.3];
    if (has_connectivity()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CellParameterSet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CellParameterSet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CellParameterSet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CellParameterSet::MergeFrom(const CellParameterSet& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cell_id()) {
      set_cell_id(from.cell_id());
    }
    if (from.has_segment_size()) {
      set_segment_size(from.segment_size());
    }
    if (from.has_segment_size_deviation()) {
      set_segment_size_deviation(from.segment_size_deviation());
    }
    if (from.has_degree()) {
      set_degree(from.degree());
    }
    if (from.has_degree_deviation()) {
      set_degree_deviation(from.degree_deviation());
    }
    if (from.has_snap_size()) {
      set_snap_size(from.snap_size());
    }
    if (from.has_snap_size_deviation()) {
      set_snap_size_deviation(from.snap_size_deviation());
    }
    if (from.has_connectivity()) {
      set_connectivity(from.connectivity());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CellParameterSet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CellParameterSet::CopyFrom(const CellParameterSet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CellParameterSet::IsInitialized() const {

  return true;
}

void CellParameterSet::Swap(CellParameterSet* other) {
  if (other != this) {
    std::swap(cell_id_, other->cell_id_);
    std::swap(segment_size_, other->segment_size_);
    std::swap(segment_size_deviation_, other->segment_size_deviation_);
    std::swap(degree_, other->degree_);
    std::swap(degree_deviation_, other->degree_deviation_);
    std::swap(snap_size_, other->snap_size_);
    std::swap(snap_size_deviation_, other->snap_size_deviation_);
    std::swap(connectivity_, other->connectivity_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CellParameterSet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CellParameterSet_descriptor_;
  metadata.reflection = CellParameterSet_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int StepSettings::kNumSegmentsFieldNumber;
const int StepSettings::kStepSizeFieldNumber;
const int StepSettings::kDeviationFieldNumber;
const int StepSettings::kRoadHeightFieldNumber;
#endif  // !_MSC_VER

StepSettings::StepSettings()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void StepSettings::InitAsDefaultInstance() {
}

StepSettings::StepSettings(const StepSettings& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void StepSettings::SharedCtor() {
  _cached_size_ = 0;
  num_segments_ = 20;
  step_size_ = 0.5f;
  deviation_ = 0.7854f;
  road_height_ = 5;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StepSettings::~StepSettings() {
  SharedDtor();
}

void StepSettings::SharedDtor() {
  if (this != default_instance_) {
  }
}

void StepSettings::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StepSettings::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StepSettings_descriptor_;
}

const StepSettings& StepSettings::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_city_2eproto();
  return *default_instance_;
}

StepSettings* StepSettings::default_instance_ = NULL;

StepSettings* StepSettings::New() const {
  return new StepSettings;
}

void StepSettings::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    num_segments_ = 20;
    step_size_ = 0.5f;
    deviation_ = 0.7854f;
    road_height_ = 5;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StepSettings::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 num_segments = 1 [default = 20];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_segments_)));
          set_has_num_segments();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_step_size;
        break;
      }

      // optional float step_size = 2 [default = 0.5];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_step_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &step_size_)));
          set_has_step_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_deviation;
        break;
      }

      // optional float deviation = 3 [default = 0.7854];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_deviation:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &deviation_)));
          set_has_deviation();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(37)) goto parse_road_height;
        break;
      }

      // optional float road_height = 4 [default = 5];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_road_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &road_height_)));
          set_has_road_height();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void StepSettings::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 num_segments = 1 [default = 20];
  if (has_num_segments()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num_segments(), output);
  }

  // optional float step_size = 2 [default = 0.5];
  if (has_step_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->step_size(), output);
  }

  // optional float deviation = 3 [default = 0.7854];
  if (has_deviation()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->deviation(), output);
  }

  // optional float road_height = 4 [default = 5];
  if (has_road_height()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->road_height(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* StepSettings::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 num_segments = 1 [default = 20];
  if (has_num_segments()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num_segments(), target);
  }

  // optional float step_size = 2 [default = 0.5];
  if (has_step_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->step_size(), target);
  }

  // optional float deviation = 3 [default = 0.7854];
  if (has_deviation()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->deviation(), target);
  }

  // optional float road_height = 4 [default = 5];
  if (has_road_height()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->road_height(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int StepSettings::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 num_segments = 1 [default = 20];
    if (has_num_segments()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->num_segments());
    }

    // optional float step_size = 2 [default = 0.5];
    if (has_step_size()) {
      total_size += 1 + 4;
    }

    // optional float deviation = 3 [default = 0.7854];
    if (has_deviation()) {
      total_size += 1 + 4;
    }

    // optional float road_height = 4 [default = 5];
    if (has_road_height()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StepSettings::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StepSettings* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StepSettings*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StepSettings::MergeFrom(const StepSettings& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_num_segments()) {
      set_num_segments(from.num_segments());
    }
    if (from.has_step_size()) {
      set_step_size(from.step_size());
    }
    if (from.has_deviation()) {
      set_deviation(from.deviation());
    }
    if (from.has_road_height()) {
      set_road_height(from.road_height());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StepSettings::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StepSettings::CopyFrom(const StepSettings& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StepSettings::IsInitialized() const {

  return true;
}

void StepSettings::Swap(StepSettings* other) {
  if (other != this) {
    std::swap(num_segments_, other->num_segments_);
    std::swap(step_size_, other->step_size_);
    std::swap(deviation_, other->deviation_);
    std::swap(road_height_, other->road_height_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StepSettings::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StepSettings_descriptor_;
  metadata.reflection = StepSettings_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TerrainSettings::kScaleFieldNumber;
const int TerrainSettings::kHeightScaleFieldNumber;
#endif  // !_MSC_VER

TerrainSettings::TerrainSettings()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TerrainSettings::InitAsDefaultInstance() {
}

TerrainSettings::TerrainSettings(const TerrainSettings& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TerrainSettings::SharedCtor() {
  _cached_size_ = 0;
  scale_ = 0;
  height_scale_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TerrainSettings::~TerrainSettings() {
  SharedDtor();
}

void TerrainSettings::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TerrainSettings::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TerrainSettings::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TerrainSettings_descriptor_;
}

const TerrainSettings& TerrainSettings::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_city_2eproto();
  return *default_instance_;
}

TerrainSettings* TerrainSettings::default_instance_ = NULL;

TerrainSettings* TerrainSettings::New() const {
  return new TerrainSettings;
}

void TerrainSettings::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    scale_ = 0;
    height_scale_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TerrainSettings::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float scale = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &scale_)));
          set_has_scale();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_height_scale;
        break;
      }

      // optional float height_scale = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_height_scale:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &height_scale_)));
          set_has_height_scale();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TerrainSettings::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional float scale = 1;
  if (has_scale()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->scale(), output);
  }

  // optional float height_scale = 2;
  if (has_height_scale()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->height_scale(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TerrainSettings::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional float scale = 1;
  if (has_scale()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->scale(), target);
  }

  // optional float height_scale = 2;
  if (has_height_scale()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->height_scale(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TerrainSettings::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional float scale = 1;
    if (has_scale()) {
      total_size += 1 + 4;
    }

    // optional float height_scale = 2;
    if (has_height_scale()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TerrainSettings::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TerrainSettings* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TerrainSettings*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TerrainSettings::MergeFrom(const TerrainSettings& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_scale()) {
      set_scale(from.scale());
    }
    if (from.has_height_scale()) {
      set_height_scale(from.height_scale());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TerrainSettings::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TerrainSettings::CopyFrom(const TerrainSettings& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TerrainSettings::IsInitialized() const {

  return true;
}

void TerrainSettings::Swap(TerrainSettings* other) {
  if (other != this) {
    std::swap(scale_, other->scale_);
    std::swap(height_scale_, other->height_scale_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TerrainSettings::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TerrainSettings_descriptor_;
  metadata.reflection = TerrainSettings_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Settings::kTerrainSettingsFieldNumber;
const int Settings::kStepSettingsFieldNumber;
const int Settings::kCellParameterSetFieldNumber;
#endif  // !_MSC_VER

Settings::Settings()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Settings::InitAsDefaultInstance() {
  terrain_settings_ = const_cast< ::citygen::protocol::TerrainSettings*>(&::citygen::protocol::TerrainSettings::default_instance());
  step_settings_ = const_cast< ::citygen::protocol::StepSettings*>(&::citygen::protocol::StepSettings::default_instance());
}

Settings::Settings(const Settings& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Settings::SharedCtor() {
  _cached_size_ = 0;
  terrain_settings_ = NULL;
  step_settings_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Settings::~Settings() {
  SharedDtor();
}

void Settings::SharedDtor() {
  if (this != default_instance_) {
    delete terrain_settings_;
    delete step_settings_;
  }
}

void Settings::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Settings::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Settings_descriptor_;
}

const Settings& Settings::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_city_2eproto();
  return *default_instance_;
}

Settings* Settings::default_instance_ = NULL;

Settings* Settings::New() const {
  return new Settings;
}

void Settings::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_terrain_settings()) {
      if (terrain_settings_ != NULL) terrain_settings_->::citygen::protocol::TerrainSettings::Clear();
    }
    if (has_step_settings()) {
      if (step_settings_ != NULL) step_settings_->::citygen::protocol::StepSettings::Clear();
    }
  }
  cell_parameter_set_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Settings::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .citygen.protocol.TerrainSettings terrain_settings = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_terrain_settings()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_step_settings;
        break;
      }

      // optional .citygen.protocol.StepSettings step_settings = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_step_settings:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_step_settings()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_cell_parameter_set;
        break;
      }

      // repeated .citygen.protocol.CellParameterSet cell_parameter_set = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_cell_parameter_set:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_cell_parameter_set()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_cell_parameter_set;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Settings::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .citygen.protocol.TerrainSettings terrain_settings = 1;
  if (has_terrain_settings()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->terrain_settings(), output);
  }

  // optional .citygen.protocol.StepSettings step_settings = 2;
  if (has_step_settings()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->step_settings(), output);
  }

  // repeated .citygen.protocol.CellParameterSet cell_parameter_set = 3;
  for (int i = 0; i < this->cell_parameter_set_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->cell_parameter_set(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Settings::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .citygen.protocol.TerrainSettings terrain_settings = 1;
  if (has_terrain_settings()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->terrain_settings(), target);
  }

  // optional .citygen.protocol.StepSettings step_settings = 2;
  if (has_step_settings()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->step_settings(), target);
  }

  // repeated .citygen.protocol.CellParameterSet cell_parameter_set = 3;
  for (int i = 0; i < this->cell_parameter_set_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->cell_parameter_set(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Settings::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .citygen.protocol.TerrainSettings terrain_settings = 1;
    if (has_terrain_settings()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->terrain_settings());
    }

    // optional .citygen.protocol.StepSettings step_settings = 2;
    if (has_step_settings()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->step_settings());
    }

  }
  // repeated .citygen.protocol.CellParameterSet cell_parameter_set = 3;
  total_size += 1 * this->cell_parameter_set_size();
  for (int i = 0; i < this->cell_parameter_set_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->cell_parameter_set(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Settings::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Settings* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Settings*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Settings::MergeFrom(const Settings& from) {
  GOOGLE_CHECK_NE(&from, this);
  cell_parameter_set_.MergeFrom(from.cell_parameter_set_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_terrain_settings()) {
      mutable_terrain_settings()->::citygen::protocol::TerrainSettings::MergeFrom(from.terrain_settings());
    }
    if (from.has_step_settings()) {
      mutable_step_settings()->::citygen::protocol::StepSettings::MergeFrom(from.step_settings());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Settings::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Settings::CopyFrom(const Settings& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Settings::IsInitialized() const {

  return true;
}

void Settings::Swap(Settings* other) {
  if (other != this) {
    std::swap(terrain_settings_, other->terrain_settings_);
    std::swap(step_settings_, other->step_settings_);
    cell_parameter_set_.Swap(&other->cell_parameter_set_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Settings::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Settings_descriptor_;
  metadata.reflection = Settings_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int City::kSettingsFieldNumber;
const int City::kNodesFieldNumber;
#endif  // !_MSC_VER

City::City()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void City::InitAsDefaultInstance() {
  settings_ = const_cast< ::citygen::protocol::Settings*>(&::citygen::protocol::Settings::default_instance());
}

City::City(const City& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void City::SharedCtor() {
  _cached_size_ = 0;
  settings_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

City::~City() {
  SharedDtor();
}

void City::SharedDtor() {
  if (this != default_instance_) {
    delete settings_;
  }
}

void City::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* City::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return City_descriptor_;
}

const City& City::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_city_2eproto();
  return *default_instance_;
}

City* City::default_instance_ = NULL;

City* City::New() const {
  return new City;
}

void City::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_settings()) {
      if (settings_ != NULL) settings_->::citygen::protocol::Settings::Clear();
    }
  }
  nodes_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool City::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .citygen.protocol.Settings settings = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_settings()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_nodes;
        break;
      }

      // repeated .citygen.protocol.Vector3 nodes = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_nodes:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_nodes()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_nodes;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void City::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .citygen.protocol.Settings settings = 1;
  if (has_settings()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->settings(), output);
  }

  // repeated .citygen.protocol.Vector3 nodes = 2;
  for (int i = 0; i < this->nodes_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->nodes(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* City::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .citygen.protocol.Settings settings = 1;
  if (has_settings()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->settings(), target);
  }

  // repeated .citygen.protocol.Vector3 nodes = 2;
  for (int i = 0; i < this->nodes_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->nodes(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int City::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .citygen.protocol.Settings settings = 1;
    if (has_settings()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->settings());
    }

  }
  // repeated .citygen.protocol.Vector3 nodes = 2;
  total_size += 1 * this->nodes_size();
  for (int i = 0; i < this->nodes_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->nodes(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void City::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const City* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const City*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void City::MergeFrom(const City& from) {
  GOOGLE_CHECK_NE(&from, this);
  nodes_.MergeFrom(from.nodes_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_settings()) {
      mutable_settings()->::citygen::protocol::Settings::MergeFrom(from.settings());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void City::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void City::CopyFrom(const City& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool City::IsInitialized() const {

  return true;
}

void City::Swap(City* other) {
  if (other != this) {
    std::swap(settings_, other->settings_);
    nodes_.Swap(&other->nodes_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata City::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = City_descriptor_;
  metadata.reflection = City_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace citygen

// @@protoc_insertion_point(global_scope)
